---
title: "Ejercicios de probabilidad"
author: "asimon"
date: "2023-07-10"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cartas al azar
### Enunciado
Se seleccionan al azar tres cartas sin reposición de una baraja que contiene 3 cartas rojas, 3 azules, 3 verdes y 3 negras. Especifica un espacio muestral para este experimento y halla todos los sucesos siguientes:

- A = "Todas las cartas seleccionadas son rojas"
- B = "Una carta es roja, 1 es verde y otra es azul"
- C = "Salen tres cartas de colores diferentes"

### Espacio muestral
Combinaciones de 4 elementos con repetición tomados 3 a 3. Con repetición.

$$\Omega = 4^3$$
### Suceso: todas las cartas son rojas
A = {RRR}
### Suceso: Una carta roja, una verde y una azul
B={
RAV
RVA
ARV
VRA
VRA
ARV
}
### Suceso: cartas de colores distintos
C = {
RAN
RAV
RNA
RNV
RVA
RVN
ARN
ARV
NRA
NRV
VRA
VRN
NRA
VRA
ARN
VRN
ARV
NRV
ANV
AVN
NAV
VAN
NVA
VAN}

## Monedas
### Enunciado
Se lanzan al aire dos monedas iguales. Hallar la probabilidad de que salgan dos caras iguales.
$P({C,C}) = 1/4$

## Dado trucado
### Enunciado
Suponer que se ha trucado un dado de modo que la probabilidad de que salga un número es proporcional al mismo.
- Hallar la probabilidad de los sucesos elementales, de que salga un número par y también de que salga un número impar.
- Repetir el problema pero suponiendo que la probabilidad de que salga un determinado número es inversamente proporcional al mismo.

### Probabilidad sucesos elementales, probabilidad proporcional
$$
P({1}) + P({2}) + P({3}) + P({4}) + P({5}) + P({6}) = 1 \\
P({2}) = 2P({1}) \\
P({3}) = 3P({1}) \\
P({4}) = 4P({1}) \\
P({5}) = 5P({1}) \\
P({6}) = 6P({1}) \\
$$

$$
21P({1}) = 1
$$

$$
\begin{matrix}
P({1}) = 1/21 \\
P({2}) = 2/21 \\
P({3}) = 3/21 \\
P({4}) = 4/21 \\
P({5}) = 5/21 \\
P({6}) = 6/21 \\
P({2,4,6}) = 12/21 \\
P({1,3,5}) = 9/21 \\
\end{matrix}
$$

### Probabilidad sucesos elementales, probabilidad inversamente proporcional
$$
P({1}) + P({2}) + P({3}) + P({4}) + P({5}) + P({6}) \\
P({2}) = P({1})/2 \\
P({3}) = P({1})/3 \\
P({4}) = P({1})/4 \\
P({5}) = P({1})/5 \\
P({6}) = P({1})/6 \\
$$

$$
\frac{49}{20}P({1}) = 1
$$
$$
\begin{matrix}
P({1}) = 20/49 \\
P({2}) = 10/49 \\
P({3}) = 20/147 \\
P({4}) = 5/49 \\
P({5}) = 4/49 \\
P({6}) = 10/147 \\
P({2,4,6}) = 55/145 \\
P({1,3,5}) = 92/147 \\
\end{matrix}
$$


## Ordenar libros en una mesa
### Enunciado
¿De cuantos modos diferentes se pueden colocar tres libros diferentes en una mesa?

### Permutación de 3 elementos
Permutación de 3 elementos: 3! = 6

## Personas en el cine
### Enunciado
Seis personas entran en el cine. ¿De cuantos modos diferentes se pueden sentar en una fila?

### Permutación de 6 elementos
Permutación de 6 elementos en 6 asientos: 6! = 720

## Premios
### Enunciado
Tres ciudadanos destacados tienen que recibir premios. Si hay 4 candidatos a dichos premios, de cuantos modos se pueden distribuir los premios:
- Si un ciudadano puede recibir como máximo un premio
- Si un ciudadano puede recibir más de un premio.

### Variaciones sin repetición
Variaciones sin repetición de 4 elementos tomados 3 a 3. V(4,3) = 4!/(4-3)! = 24.

### Variaciones con repetición
Variaciones con repetición de 4 elementos tomados 3 a 3. VR(4,3) = 4^3 = 64.

## Unir los puntos
### Enunciado
Dado un conjunto de 15 puntos del plano, ¿cuantas líneas se necesitan para juntar todos los posibles pares de puntos?

### Combinaciones
Combinaciones sin repetición, el orden de los pares no importa. C(15,2)=15! /(2!(15-2)!) = 105.

## Bombillas
### Enunciado
Dada una caja con los siguientes focos; 2 de 25 vatios, 4 de 40 vatios y 4 de 100 vatios, ¿de cuantos modos se pueden elegir 3 de ellos?

### Combinaciones con repetición
Los 3 focos del mismo tipo, sólo pueden ser de 40 vatios y 100 vatios. Combinaciones con repetición de 3 elementos tomados 3 a 3, menos el caso de 3 focos de 25 W: CR(3,3) = 5!/(3!(5-3)!) - 1  =10 - 1 = 9.

## Matrículas
### Enunciado
Supongamos que las placas de matrícula de coches se componen de tres letras seguidas de tres dígitos. Si se pueden usar todas las combinaciones posibles, ¿cuantas placas diferentes se podrían formar?

### Variaciones con repetición
Variaciones con repetición de 26 letras tomadas 3 a 3, y 10 dígitos tomados 3 a 3
VR(26,3) * (VR(10,3) = 26^3 * 10^3 = 175760000 matrículas.

## Equipos en una liga
### Enunciado
De cuantos modos diferentes se pueden enfrentar en un partido 2 equipos de una liga que tenga 8?

### Combinaciones sin repetición
Combinaciones sin repetición de 8 elementos tomados 2 a 2. C(8,2) = 8!/(2!(8-2)!) = 28

## Cajas de colores
### Enunciado
En un almacen hay cajas rojas y verdes.
- ¿De cuantas formas se pueden colocar en fila 20 cajas si 15 son rojas y 5 son verdes?
- ¿Y si hay 10 de cada color?

### Permutaciones con repetición
Permutaciones con repetición de 20 elementos, en grupos de 15 y 5 PR(20,15,5) = 20!/(15!5!) = 15504

### Permutaciones con repetición
Permutaciones con repetición de 20 elementos, en grupos de 10 y 0 PR(20,10,10) = 20!/(10!0!) = 184756

## Prisión
### Enunciado
En una prisión de 100 presos se seleccionan al azar dos personas para ponerlas en libertad.
- ¿Cual es la probabilidad de que el más viejo de los presos sea uno de los elegidos?
- ¿Y que salga elegida la pareja formada por el más viejo y el más joven?

### Espacio muestral
El espacio muestral son combinaciones de 100 elementos tomados 2 a dos. C(100,2) = 100!/(2!(100-2)!) = 4950

### Probabilidad más viejo
De todas las combinaciones en 99 está el preso más viejo. P(Viejo) = 99/4950

### Probabilidad más joven y más viejo
De todas las combinaciones, sólo en una están el preso más viejo y el más joven. P(Viejoven) = 1/4950